CFLAGS=-Wall -g # -g flag to get debuggin
 
clean:      # calleable by make
	rm -f ex1 # TAB ONLY...put as many shell cmds here to automage
	rm -f ex3 # TAB ONLY...put as many shell cmds here to automage
all:
	make ex1
	make ex3
